include:
  - ./networks/docker-compose.yml
  - ./secrets/docker-compose.yml
  - ./volumes/docker-compose.yml

services:
  mariadb:
    build:
      context: ${MDB_BUILD_CONTEXT}
      dockerfile: ${MDB_DOCKERFILE}
    image: ${DB_IMAGE_NAME}
    container_name: ${MDB_CONTAINER_NAME}
    env_file:
      - ${MDB_CONFIG_ENV}
    secrets:
      - mysql_root_password
      - mysql_wp_db_admin_password
    restart: always
    networks:
      backend_net:
        ipv4_address: ${NETWORK_BACKEND_DB_IP}
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - ${VOLUME_DB_NAME}:${VOLUME_DB_MOUNTPOINT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  wordpress-php:
    build:
        context: ${WP_BUILD_CONTEXT}
        dockerfile: ${WP_DOCKERFILE}
        args:
          DOMAIN_NAME: ${DOMAIN_NAME}
          PHP_FPM_VERSION: ${PHP_FPM_VERSION}
    image: ${WP_IMAGE_NAME}
    container_name: ${WP_CONTAINER_NAME}
    env_file:
      - ${WP_CONFIG_ENV}
    secrets:
      - mysql_wp_db_admin_password
      - wp_admin_password
      - wp_user_password
    networks:
      frontend_net:
        ipv4_address: ${NETWORK_FRONTEND_PHPFPM_IP}
      backend_net:
        ipv4_address: ${NETWORK_BACKEND_PHPFPM_IP}
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "${PHPFPM_LISTEN_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ${VOLUME_WP_NAME}:${VOLUME_WP_MOUNTPOINT}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    build:
      context: ${NGINX_BUILD_CONTEXT}
      dockerfile: ${NGINX_DOCKERFILE}
      args:
        KEY_NAME: ${KEY_NAME}
        CERT_NAME: ${CERT_NAME}
    image: ${NGINX_IMAGE_NAME}
    container_name: ${NGINX_CONTAINER_NAME}
    env_file:
      - ${NGINX_CONFIG_ENV}
    secrets:
      - ssl_key
      - ssl_cert
    ports:
      - "${NGINX_HOST_PORT}:${NGINX_LISTEN_PORT}"
    networks:
      frontend_net:
        ipv4_address: ${NETWORK_FRONTEND_NGINX_IP}
    depends_on:
      wordpress-php:
        condition: service_healthy
    volumes:
      - ${VOLUME_WP_NAME}:${VOLUME_WP_MOUNTPOINT}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
