include:
  - networks/docker-compose.yml
  - secrets/docker-compose.yml

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception
    container_name: mariadb
    env_file:
      - ./requirements/mariadb/config.env
    secrets:
      - mysql_root_password
      - mysql_wp_db_admin_password
    restart: always
    networks:
      backend_net:
        ipv4_address: 172.28.0.2

  wordpress-php:
    image: wordpress:php8.2-fpm
    container_name: wordpress-php
    networks:
      frontend_net:
        ipv4_address: 172.28.0.18
      backend_net:
        ipv4_address: 172.28.0.3
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        KEY_NAME: ${KEY_NAME}
        CERT_NAME: ${CERT_NAME}
    image: nginx:inception
    container_name: nginx
    env_file:
      - ./requirements/nginx/config.env
    ports:
      - "8080:80"
      - "4343:443"
    networks:
      frontend_net:
        ipv4_address: 172.28.0.19
    restart: always