secrets:

  wp_admin_password:
    file: ../secrets/wordpress-php/wp_admin_password.secret

  wp_user_password:
    file: ../secrets/wordpress-php/wp_user_password.secret

  wp_admin_username:
    file: ../secrets/wordpress-php/wp_admin_username.secret

  wp_user_username:
    file: ../secrets/wordpress-php/wp_user_username.secret

  wp_admin_mail:
    file: ../secrets/wordpress-php/wp_admin_mail.secret

  wp_user_mail:
    file: ../secrets/wordpress-php/wp_user_mail.secret

  mysql_root_password:
    file: ../secrets/mariadb/mysql_root_password.secret

  mysql_wp_db_admin_password:
    file: ../secrets/mariadb/mysql_wp_db_admin_password.secret

  mysql_wp_db_admin_username:
    file: ../secrets/mariadb/mysql_wp_db_admin_username.secret

  ssl_key:
    file: ../secrets/ssl/${KEY_NAME}

  ssl_cert:
    file: ../secrets/ssl/${CERT_NAME}
