secrets:

  wp_admin_password:
    file: ../secrets/wordpress-php/wp_admin_password.secret

  wp_user_password:
    file: ../secrets/wordpress-php/wp_user_password.secret

  mysql_root_password:
    file: ../secrets/mariadb/mysql_root_password.secret

  mysql_wp_db_admin_password:
    file: ../secrets/mariadb/mysql_wp_db_admin_password.secret

  ssl_key:
    file: ../secrets/ssl/${KEY_NAME}

  ssl_cert:
    file: ../secrets/ssl/${CERT_NAME}
