networks:

  # Configuration for backend network
  backend_net:
    name: backend_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: ${NETWORK_BACKEND_SUBNET} # 16-31
          gateway: ${NETWORK_BACKEND_GATEWAY}

  # Configuration for the frontend network
  frontend_net:
    name: frontend_net
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: ${NETWORK_FRONTEND_SUBNET} # 0-15
          gateway: ${NETWORK_FRONTEND_GATEWAY}