secrets:

  wp_admin_password:
    file: ./wordpress-php/wp_admin_password.secret

  wp_user_password:
    file: ./wordpress-php/wp_user_password.secret

  mysql_root_password:
    file: ./mariadb/mysql_root_password.secret

  mysql_wp_db_admin_password:
    file: ./mariadb/mysql_wp_db_admin_password.secret

  ssl_key:
    file: ./ssl/${KEY_NAME}

  ssl_cert:
    file: ./ssl/${CERT_NAME}
