secrets:

  wp_admin_password:
    file: ./wordpress-php/wp_admin_password

  wp_user_password:
    file: ./wordpress-php/wp_user_password

  mysql_root_password:
    file: ./mariadb/mysql_root_password

  mysql_wp_db_admin_password:
    file: ./mariadb/mysql_wp_db_admin_password
